name: tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      #- name: Checkout
      #  uses: actions/checkout@v1
      # https://github.com/cypress-io/github-action
      - name: Checkout cypress repository
        uses: actions/checkout@v3
        with:          
          repository: kuriakose-thomas/cypress-code
          #ref: ${{env.CYPRESS_RESPOSITORY_BRANCH}}
          #token: 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 #${{secrets.ORG_SCOPED_GITHUB_TOKEN}}
      
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          record: true
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
